### ISSUE TITLE
Where can I download BitmapToCArray?

### ISSUE THREAD

**Issue by maxbad** [greyb1t/gwingui_v2#1]
Is this small program provided?

**Comment by greyb1t** [comment]
I just wanna make sure you are aware that the library has not been made with the intention for other people to use.
You might find that it is hard to use, or simply just unusable due to the low quality of the code.

Either way, here's the code for the BitmapToCArray if you want it.

https://gist.github.com/greyb1t/9845a541bc524b27fcf424ecff62f5ce

**Comment by maxbad** [comment]
Could you tell me if this library will continue to update more components?
